packages:
  - .
  - 'packages/*'

catalog:
  '@antfu/eslint-config': ^7.6.1
  '@babel/cli': ^7.0.0
  '@babel/core': ^7.0.0
  '@babel/preset-env': ^7.3.4
  '@eslint-react/eslint-plugin': ^2.13.0
  '@types/node': ^20.11.30
  '@types/react': ^16.x
  '@types/react-test-renderer': ^16.x
  '@vitest/coverage-v8': ^4.0.18
  '@vitest/ui': ^4.0.18
  co: ^4.6.0
  eslint: ^10.0.2
  eslint-plugin-format: ^2.0.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.5.2
  husky: ^7.0.4
  lint-staged: ^12.1.2
  prettier: ^3.8.0
  react: ^16.x
  react-test-renderer: ^16.x
  reflect-metadata: ^0.2.2
  rimraf: ^6.0.0
  typescript: ~5.0
  vitest: ^4.0.18